name: 'Hakan Gulgonul '
favicon: null
layout_spectrum: 0.46404
typography_spectrum: 0.59845
title: "it's hard to dance with the devil on your back"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbd920'
    - '#000000'
    - '#565656'
    - '#a8973b'
    - '#fded97'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
