name: 'Hakan Gulgonul '
favicon: null
layout_spectrum: 0.23887
typography_spectrum: 0.59845
title: "it's hard to dance with the devil on your back"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030301'
    - '#c1c1bf'
    - '#2f2f33'
    - '#82837d'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
