name: 'Hakan Gulgonul '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59845
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f0f'
    - '#fefefe'
    - '#3c3c3c'
    - '#7c7c7c'
    - '#c3c3c3'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
